"""Catalog scenario schema.

A `ScenarioSpec` is a self-contained, reproducible recipe for one Dispatch
Arena episode. The simulator-relevant fields map 1:1 onto
`dispatch_arena.models.Config` plus a `seed`. The narrative fields
(`theme`, `description`, `skill_focus`, ...) are storytelling metadata used
by the trainer for per-bucket logging and by the README/replay UI.

Schema is intentionally flat and JSON-serializable so the catalog can live
on disk under `dispatch_arena/catalog/catalog.json` and be regenerated by
either the Claude-powered builder or the deterministic anchor builder.
"""

from __future__ import annotations

from typing import List, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from dispatch_arena.models import Config, Mode

Difficulty = Literal["easy", "medium", "hard"]

# Skill tags double as eval-time bucketing labels. Keep this list tight —
# every tag should map to a measurable competence the trainer can report on.
SkillTag = Literal[
    "prep_uncertainty",      # hidden prep_remaining is the dominant bottleneck
    "rolling_arrivals",      # orders appear during the shift, not at t=0
    "traffic_noise",         # actual ETAs differ from the published matrix
    "deadline_pressure",     # tight SLAs relative to travel + prep
    "courier_load_balance",  # imbalance penalty matters; many couriers
    "long_tail_routing",     # a small number of orders are far from everything
    "shifted_distribution",  # OOD-flavored prep / deadline distributions
]


class ScenarioSpec(BaseModel):
    """One catalog entry. Pickled to JSON as-is."""

    model_config = ConfigDict(use_enum_values=False, extra="forbid")

    # --- Identity / narrative ----------------------------------------------
    name: str = Field(..., description="Unique snake_case identifier")
    difficulty: Difficulty
    theme: str = Field(..., description='Short narrative label, e.g. "Friday dinner rush"')
    description: str = Field(..., description="One paragraph: what the shift looks like and why it is hard")
    skill_focus: List[SkillTag] = Field(default_factory=list)

    # --- Simulator config (drives env.reset) -------------------------------
    seed: int
    mode: Literal["normal"] = "normal"
    max_ticks: int
    num_couriers: int
    num_orders: int
    scenario_bucket: Literal["easy", "tight", "long_tail", "shifted_distribution"]
    rolling_arrivals: bool
    traffic_noise: float
    visible_prep: bool = False

    # --- Storytelling (not consumed by simulator) --------------------------
    expected_failure_modes: List[str] = Field(default_factory=list)
    success_criteria: str = ""

    @model_validator(mode="after")
    def _validate(self) -> "ScenarioSpec":
        if self.num_couriers < 2 or self.num_couriers > 5:
            raise ValueError(f"num_couriers must be in [2,5], got {self.num_couriers}")
        if self.num_orders < 3 or self.num_orders > 10:
            raise ValueError(f"num_orders must be in [3,10], got {self.num_orders}")
        if self.max_ticks < 8 or self.max_ticks > 30:
            raise ValueError(f"max_ticks must be in [8,30], got {self.max_ticks}")
        if self.traffic_noise < 0.0 or self.traffic_noise > 1.0:
            raise ValueError(f"traffic_noise must be in [0,1], got {self.traffic_noise}")
        if not self.name.replace("_", "").isalnum():
            raise ValueError(f"name must be snake_case alphanumeric, got {self.name!r}")
        return self

    def to_config(self) -> Config:
        """Build the simulator Config that this spec represents."""
        return Config(
            mode=Mode.NORMAL,
            max_ticks=self.max_ticks,
            num_couriers=self.num_couriers,
            num_orders=self.num_orders,
            scenario_bucket=self.scenario_bucket,
            rolling_arrivals=self.rolling_arrivals,
            traffic_noise=self.traffic_noise,
            visible_prep=self.visible_prep,
        )
